# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6rPYHSYEt0y2Up_aCHh6s-kNUE-q8Ow
"""



import pandas as pd

df = pd.read_csv("/FoodBalanceSheets_E_Africa_NOFLAG.csv",encoding='latin-1')
print(df)

df.groupby('Area')['Area'].count()

df1=df.groupby('Y2014')['Y2014'].count()
df1

df1.isnull().sum()

df2=df.groupby('Element')['Element'].count()
df2



